#Problem 33: Write a function nearly_equal to test whether two strings are nearly equal. Two strings a and b are nearly equal when a can be generated by a single mutation on b.

from ch2_prob32 import mutate

def nearly_equal(s,m):
	mutated=mutate(s)
	return m in mutated

def main():
	print nearly_equal('hello','ello')
	
if __name__ == '__main__':
    main()
